image: python:3
lint:
 stage: build
 script:
 - pip install yapf==0.32.0
 - yapf --recursive . --diff --style google
 only:
 - pushes

 unittest:
 stage: test
 needs:
 - pipeline: build
   job: lint
 script:
 - pip install -r requirements.txt
 - pytest -v
 only:
 - pushes